#!/bin/sh

project=$(find "$HOME" -type d -print | fzf)

if [ -z "$project" ]; then
    echo "No project selected."
    exit 1
fi

session_name=$(basename "$project")

if tmux has-session -t "$session_name" 2>/dev/null; then
    tmux attach -t "$session_name"
else
    tmux new-session -s "$session_name" -c "$project" "nvim; zsh; tmux kill-session -t $session_name"
fi
