#!/bin/bash

DOWNLOAD_DIR=~/Videos

url=$(xclip -o -selection clipboard)
if [[ -z "$url" ]]; then
    echo "No URL found in the clipboard!"
    exit 1
fi

quality=$(echo -e "144p\n360p\n720p\n1080p\naudio" | dmenu -p "Select Quality:")
if [[ -z "$quality" ]]; then
    echo "No quality selected!"
    exit 1
fi

mkdir -p "$DOWNLOAD_DIR"

case "$quality" in
    "144p") format="bestvideo[height<=144]+bestaudio/best[height<=144]" ;;
    "360p") format="bestvideo[height<=360]+bestaudio/best[height<=360]" ;;
    "720p") format="bestvideo[height<=720]+bestaudio/best[height<=720]" ;;
    "1080p") format="bestvideo[height<=1080]+bestaudio/best[height<=1080]" ;;
    "audio") format="bestaudio" ;;
    *) echo "Invalid quality selected!" ; exit 1 ;;
esac

if [[ "$quality" == "audio" ]]; then
	yt-dlp --force-overwrites -x --audio-format mp3 -o "$DOWNLOAD_DIR/%(title)s.%(ext)s" "$url"
	filepath=$(yt-dlp -x --audio-format mp3 -o "$DOWNLOAD_DIR/%(title)s.%(ext)s" "$url" --get-filename)
	filepath="$(dirname "$filepath")/$(basename "$filepath" .${filepath##*.}).mp3"
else
	yt-dlp --force-overwrites -f "$format" -o "$DOWNLOAD_DIR/%(title)s.%(ext)s" "$url"
	filepath=$(yt-dlp -f "$format" -o "$DOWNLOAD_DIR/%(title)s.%(ext)s" "$url" --get-filename)
fi

echo "Download complete! Files saved in $DOWNLOAD_DIR"

mpv "$filepath"&

