#!/bin/bash

# SSID="zbook"
# PASSWORD="pa\$\$word"
ACCESS_CODE="0000"
#
# if ! nmcli con show | grep -q "$SSID"; then
#     doas nmcli device wifi hotspot con-name "$SSID" ssid "$SSID" band bg password "$PASSWORD"
# fi

adb reverse tcp:1701 tcp:1701
adb reverse tcp:9001 tcp:9001
# nmcli con up "$SSID"
# weylus --auto-start --no-gui --try-nvenc --access-code $ACCESS_CODE
weylus --auto-start --no-gui --access-code $ACCESS_CODE
# nmcli con down "$SSID"

